services:
  station:
    container_name: ${POD_NAME}
    hostname: ${POD_HOSTNAME}
    image: ${POD_IMAGE}
    restart: always
    mem_limit: ${POD_MEM}
    cpus: ${POD_CPU}
    ports:
      - "8001:8080"
    volumes:
      - ${POD_DATA_WORK}:/work
      - ${POD_DATA_ROOT}:/root
      - /var/run/docker.sock:/var/run/docker.sock
      - /app:/app
    
